import { readFile, writeFile } from "node:fs/promises"
import { dirname, join } from "node:path"

const scriptDir = dirname(new URL(import.meta.url).pathname)
const packageRoot = join(scriptDir, "..")
const repoRoot = join(packageRoot, "..", "..")
const tslRoot = join(repoRoot, "src", "renderer", "shaders", "tsl")

const UTIL_SECTION_ORDER = [
  "noise",
  "color",
  "patterns",
  "sdf",
  "complex",
  "math",
] as const

type UtilSectionName = (typeof UTIL_SECTION_ORDER)[number]

function classifyModulePath(modulePath: string): UtilSectionName {
  if (modulePath.includes("/noise/")) {
    return "noise"
  }

  if (modulePath.includes("/color/") || modulePath.includes("cosine-palette")) {
    return "color"
  }

  if (modulePath.includes("/patterns/")) {
    return "patterns"
  }

  if (modulePath.includes("/utils/sd-")) {
    return "sdf"
  }

  if (modulePath.includes("/utils/complex-")) {
    return "complex"
  }

  return "math"
}

function stripImportLines(source: string): string {
  return source
    .split("\n")
    .filter((line) => !/^\s*import[\s{]/.test(line))
    .join("\n")
    .trimStart()
}

async function readUtilEntries() {
  const barrelSource = await readFile(join(tslRoot, "utils", "index.ts"), "utf8")
  const exportPattern =
    /export\s*\{([^}]+)\}\s*from\s*"@\/renderer\/shaders\/tsl\/([^"]+)"/g
  const sections: Record<string, unknown[]> = {}

  for (const name of UTIL_SECTION_ORDER) {
    sections[name] = []
  }

  for (const match of barrelSource.matchAll(exportPattern)) {
    const namesGroup = match[1]
    const modulePath = match[2]

    if (!(namesGroup && modulePath)) {
      continue
    }

    const exportNames = namesGroup
      .split(",")
      .map((name) => name.trim())
      .filter((name) => name.length > 0)
    const section = classifyModulePath(`/${modulePath}`)
    const relativePath = modulePath.replace("renderer/shaders/tsl/", "")
    const source = stripImportLines(
      await readFile(join(tslRoot, `${relativePath}.ts`), "utf8")
    )

    sections[section]?.push({ exportNames, modulePath, source })
  }

  return sections
}

async function readStarters() {
  const shared = await readFile(
    join(repoRoot, "src", "lib", "editor", "custom-shader", "shared.ts"),
    "utf8"
  )
  const extract = (constant: string): string => {
    const pattern = new RegExp(`export const ${constant} = \`([\\s\\S]*?)\`\\n`)

    return shared.match(pattern)?.[1] ?? "// starter unavailable"
  }

  return {
    effect: extract("CUSTOM_EFFECT_STARTER"),
    source: extract("CUSTOM_SHADER_STARTER"),
  }
}

async function readTslExportNames(): Promise<string[]> {
  const module = await import("three/tsl")

  return Object.keys(module).sort()
}

const [utilEntries, starters, tslExportNames] = await Promise.all([
  readUtilEntries(),
  readStarters(),
  readTslExportNames(),
])

const total = Object.values(utilEntries).reduce(
  (sum, entries) => sum + entries.length,
  0
)

if (total === 0 || tslExportNames.length === 0) {
  throw new Error(
    `Reference snapshot looks empty (${total} utils, ${tslExportNames.length} tsl exports). Run this from inside the shader-lab repo.`
  )
}

const banner = `// Generated by scripts/generate-reference-data.ts — do not edit by hand.
// Regenerate with: bun run --cwd packages/shader-lab-mcp generate
`

const body = `${banner}
export interface GeneratedUtilEntry {
  exportNames: string[]
  modulePath: string
  source: string
}

export const UTIL_ENTRIES: Record<string, GeneratedUtilEntry[]> = ${JSON.stringify(utilEntries, null, 2)}

export const STARTERS: { effect: string; source: string } = ${JSON.stringify(starters, null, 2)}

export const TSL_EXPORT_NAMES: string[] = ${JSON.stringify(tslExportNames, null, 2)}
`

await writeFile(
  join(packageRoot, "src", "lib", "shader-reference-data.ts"),
  body,
  "utf8"
)

process.stderr.write(
  `[shader-lab-mcp] reference snapshot: ${total} utils, ${tslExportNames.length} tsl exports\n`
)
